// @no-log
# curl POST localhost:8080/register -H "Content-Type: application/json" --data '{"username":"xyz","password":"xyz"}'
POST localhost:8080/register?trace=true
Content-Type: application/json

{
  "username": "hakan",
  "password": "xyz"
}

###
//@no-log
# curl POST localhost:8080/authenticate  -H "Content-Type: application/json" --data '{  "username": "hakan", "password": "xyz"}'
POST localhost:8080/authenticate
Content-Type: application/json

{
  "username": "hakan",
  "password": "xyz"
}

###

//@no-log

GET localhost:8080/hello-world
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoYWthbiIsImV4cCI6MTY2MjMyOTE3MCwiaWF0IjoxNjYyMzA3NTcwfQ.nSdWMZE9p0vqpbfikVDMsdNbxYdaQpQYWbGY2fNbaVyq1wZMqFEyLv77bFK1Kl3y2pCMUTxx6oQ-djCYF7Dz5w

